a=input("nhập vào chuỗi s1:")
b=input("Nhập vào chuỗi s2:")
c=input("Nhập vào chuỗi s2:")
d=int(input("Nhập vào index:"))
print("chiều dài chuỗi s1=",len(a))
print("chiều dài chuỗi s2=",len(b))
print("chiều dài chuỗi s3=",len(c))
print("chuỗi s4 =",a[d:])
print("chuỗi s2 lập lại 2 lần",b*2)